import 'package:flutter/material.dart';

import '../data/models/project.dart';

const List<Project> projects = [
  Project(
    title: 'CHEFAA',
    category: 'Healthcare Platform',
    description: 'A multi-role healthcare application connecting patients, doctors, pharmacies, laboratories, and medical imaging services within one digital ecosystem.',
    technologies: [
      'Flutter',
      'Dart',
      'BLoC',
      'Cubit',
      'Dio',
      'REST APIs',
      'Firebase',
      'JWT',
      'GetIt',
    ],
    icon: Icons.local_hospital_rounded,
    github: 'https://github.com/Emo2003/chefaa',
    liveDemoUrl: null,
    featured: true,
    coverImage: 'assets/images/chefaa.png',
    problem: 'Healthcare services are often distributed across different platforms, making it difficult for users to manage appointments, medications, laboratory services, and medical communication in one place.',
    idea: 'Create a unified healthcare experience that allows patients to access essential healthcare services through a clear and connected journey.',
    solution: 'A multi-role healthcare platform with appointment management, medication and prescription handling, pharmacy services, laboratory services, medical imaging, notifications, and healthcare communication.',
    role: 'I worked on the Flutter mobile application, focusing on UI implementation, architecture, state management, API integration, and creating clear user flows.',
    features: [
      'Patient Management',
      'Doctor Appointments',
      'Medication Management',
      'Prescriptions',
      'Pharmacy Services',
      'Laboratory Services',
      'Medical Imaging',
      'Notifications',
      'Authentication',
      'REST API Integration',
      'Chatbot / AI Functionality',
    ],
    architecture: 'Clean Architecture',
    stateManagement: 'BLoC / Cubit',
    apiIntegration: 'REST APIs, Dio, Firebase, JWT Authentication',
    challenges: 'Designing a modular structure for multiple healthcare journeys while keeping the architecture maintainable and the API integration consistent.',
    learnings: 'Strengthened my understanding of scalable Flutter architecture, state management, role-based flows, API integration, and building realistic product experiences.',
    outcome: 'A realistic healthcare product concept demonstrating structured architecture, multiple service flows, and a user-focused mobile experience.',
  ),

  Project(
    title: 'Ema Store',
    category: 'E-Commerce',
    description: 'A Flutter e-commerce application focused on product discovery, categories, search, authentication, product details, and cart management.',
    technologies: [
      'Flutter',
      'Dart',
      'REST APIs',
      'Dio',
      'Cubit',
      'Clean Architecture',
    ],
    icon: Icons.shopping_bag_rounded,
    github: 'https://github.com/Emo2003/ema_store',
    liveDemoUrl: null,
    featured: false,
    coverImage: 'assets/images/store.png',
    problem: 'E-commerce applications need clear product discovery and a smooth shopping flow while keeping product and cart information easy to access.',
    idea: 'Build a simple and intuitive shopping experience centered around products and clear user journeys.',
    solution: 'A product-focused Flutter application with categories, search, product details, authentication, cart management, and shipping address handling.',
    role: 'Worked on the application UI, state management, API integration, and implementation of the main shopping flows.',
    features: [
      'Product Browsing',
      'Categories',
      'Product Details',
      'Search',
      'Authentication',
      'Cart Management',
      'Shipping Address',
      'API Integration',
    ],
    architecture: 'Clean Architecture',
    stateManagement: 'Cubit',
    apiIntegration: 'REST API with Dio',
    challenges: 'Managing product and cart states across multiple screens while keeping the shopping flow simple and responsive.',
    learnings: 'Improved my understanding of state management, API integration, cart flows, and structuring maintainable Flutter applications.',
    outcome: 'A practical e-commerce application demonstrating product browsing, authentication, cart management, and API-driven functionality.',
  ),

  Project(
    title: 'Cinemax',
    category: 'Movie Application',
    description: 'A movie discovery application with modern UI, category browsing, search, movie details, and API-driven content.',
    technologies: ['Flutter', 'Dart', 'BLoC', 'REST API', 'GetIt', 'Dio'],
    icon: Icons.movie_rounded,
    github: 'https://github.com/Emo2003/movie_app',
    liveDemoUrl: null,
    featured: false,
    coverImage: 'assets/images/movies.png',
    features: [
      'Movie Browsing',
      'Movie Details',
      'Categories',
      'Search',
      'API Integration',
      'Modern UI',
    ],
    architecture: 'Modular Flutter App Structure',
    stateManagement: 'BLoC',
    apiIntegration: 'REST API with Dio',
    challenges: 'Implementing search and category-based discovery while maintaining a clean and responsive interface.',
    learnings: 'Improved my understanding of content-driven interfaces, API integration, BLoC state management, and dynamic data presentation.',
  ),

  Project(
    title: 'Quiz Application',
    category: 'Interactive Application',
    description: 'An interactive Flutter quiz application featuring dynamic questions, answer selection, score calculation, and a clear results experience.',
    technologies: ['Flutter', 'Dart', 'OOP'],
    icon: Icons.quiz_rounded,
    github: 'https://github.com/Emo2003/QuizApp',
    liveDemoUrl: null,
    featured: false,
    coverImage: 'assets/images/quiz.png',
    features: [
      'Dynamic Questions',
      'Answer Selection',
      'Score Calculation',
      'Interactive UI',
      'Result Screen',
    ],
    architecture: 'Simple Flutter App Structure',
    stateManagement: 'State-Driven UI Logic',
    apiIntegration: 'No External API Required',
    challenges: 'Creating a simple and intuitive quiz flow with clear feedback and smooth interactions.',
    learnings: 'Strengthened my understanding of Flutter UI interactions, application flow, conditional logic, and state-driven interfaces.',
  ),
];
